### ISSUE TITLE
Problem mit Modell-Bild overlay

### ISSUE THREAD

**Issue by juliandehne** [wiepke/spiderweb#63]
http://fleckenroller.cs.uni-potsdam.de/fides/mikrodisplayger.php?mikroid=94&mesoid=85#
wenn man das Bild zweimal anklickt, dann wird es zweimal darübergeladen. Wenn man noch einmal auf den button klickt, sollte das Bild verschwinden.

**Comment by Clickmari** [comment]
klick doch nur einmal bitte... ich gucke
