### ISSUE TITLE
Optik

### ISSUE THREAD

**Issue by annaheudorfer** [wiepke/spiderweb#79]
Gibt es einen Grund, warum das letzte Dialogfeld (Sie erhalten nun auf Basis Ihrer Eingaben eine grafische Darstellung...) blau hinterlegt ist?

Ergebnisgrafik: Gibt es einen Grund, warum der innere Kreis wesentlich größer ist als die äußeren?

**Comment by wiepke** [comment]
Den blauen Hintergrund in "Sie erhalten nun auf Basis Ihrer eingaben eine grafische Darstellung..." habe ich entfernt, da ich auch keine Verwendung dafür sah.

Der innere Kreis der Grafik ist so viel größer um auf das Modell-Bild zu passen. Wenn man das Modell einblendet über den blauen Text "Modell einblenden, um zu vergleichen" sieht man, dass alle Dimensionen mit dem des Modells auf einer Linie liegen. Kann ich natürlich auch wieder ändern, wenn es nicht gewünscht ist =)
